version: '3.8'

services:
  web:
    image: python:3.11-slim
    container_name: django_app
    restart: always
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      bash -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py process_tasks &
      gunicorn --bind 0.0.0.0:8000 --workers 3 myproject.wsgi:application
      "

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: rowg
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
