services:
  web:
    build: .
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      bash -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py process_tasks &
      gunicorn --bind 0.0.0.0:8000 --workers 3 zaffar.wsgi:application
      "

volumes:
  - .:/app
